apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    app: {{ include "frontend.fullname" . }}
    instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "frontend.fullname" . }}
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "frontend.fullname" . }}
        instance: {{ .Release.Name }}
    spec:
      containers:
        - name: frontend
          image: {{ printf "%s:%s" .Values.frontend.image.name .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              name: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
            - name: TURN_URI
              value: {{ .Values.turn.uri | quote }}
