apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.fullname" . }}
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.frontend.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.frontend.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "frontend.fullname" . }}
                port:
                  number: {{ .Values.frontend.port }}
          - path: /{{ .Values.signalling.ws.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "signalling.fullname" . }}
                port:
                  number: {{ .Values.signalling.ws.port }}
