apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" .}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "frontend.fullname" . }}
    instance: {{ .Release.Name }}
