webrtc:
  name: solo

ingress:
  tlsSecret: solo.yon.si-tls

frontend:
  replicas: 1
  host: solo.yon.si
  image:
    name: plojyon/solo-frontend
    tag: latest
    pullPolicy: Always
  port: 8080
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

signalling:
  replicas: 1
  host: solo.yon.si
  ws:
    path: ws
    port: 3000
  image:
    name: plojyon/solo-signal
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
