webrtc:
  name: solo

ingress:
  tlsSecret: solo.yon.si-tls

frontend:
  replicas: 1
  host: solo.yon.si
  image:
    name: plojyon/solo-frontend
    tag: latest
    pullPolicy: Always
  port: 8080
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

turn:
  uri: "turn.solo.yon.si"

